{% set name = "qtpynodeeditor" %}
{% set python_min = "3.9" %}
{% set version = "0.3.3" %}
{% set sha256 = "88830423efbb870e5ec887b9e159e47ba314f04e4efb280cd90f9eae40b91e7a" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools_scm
    - setuptools
  run:
    - python >={{ python_min }}
    - qtpy
    - pyqt
    - qt

test:
  requires:
    - python {{ python_min }}
  imports:
    - qtpynodeeditor
    - qtpynodeeditor.examples
    - qtpynodeeditor.tests

about:
  home: https://github.com/klauer/qtpynodeeditor
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Python Qt node editor
  doc_url: https://klauer.github.io/qtpynodeeditor/

extra:
  recipe-maintainers:
    - klauer
